// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api/postmates.proto

package postmates

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PostmatesClient is the client API for Postmates service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostmatesClient interface {
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
}

type postmatesClient struct {
	cc grpc.ClientConnInterface
}

func NewPostmatesClient(cc grpc.ClientConnInterface) PostmatesClient {
	return &postmatesClient{cc}
}

func (c *postmatesClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, "/Postmates/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostmatesServer is the server API for Postmates service.
// All implementations must embed UnimplementedPostmatesServer
// for forward compatibility
type PostmatesServer interface {
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	mustEmbedUnimplementedPostmatesServer()
}

// UnimplementedPostmatesServer must be embedded to have forward compatible implementations.
type UnimplementedPostmatesServer struct {
}

func (UnimplementedPostmatesServer) Signup(context.Context, *SignupRequest) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedPostmatesServer) mustEmbedUnimplementedPostmatesServer() {}

// UnsafePostmatesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostmatesServer will
// result in compilation errors.
type UnsafePostmatesServer interface {
	mustEmbedUnimplementedPostmatesServer()
}

func RegisterPostmatesServer(s grpc.ServiceRegistrar, srv PostmatesServer) {
	s.RegisterService(&Postmates_ServiceDesc, srv)
}

func _Postmates_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostmatesServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Postmates/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostmatesServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Postmates_ServiceDesc is the grpc.ServiceDesc for Postmates service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Postmates_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Postmates",
	HandlerType: (*PostmatesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _Postmates_Signup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/postmates.proto",
}
